### ISSUE TITLE
你们团队真的是太聪明了，这么好的解决方案。我有一个地方没看懂，还请指明

### ISSUE THREAD

**Issue by shoutOutYangJie** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#1]
大赛给的样本都是打了水印的。想用GAN去生成没有水印的图像，首先就要有没有水印的标签，而且还要满足仅仅没有水印，其他位置和带有水印一致。 你们是怎么获得这样的数据的？

**Comment by Mingtzge** [comment]
你好,我们是通过生成仿真数据集的方式来获得去水印的训练数据的.[生成仿真数据源码](https://github.com/Mingtzge/2019-CCF-BDCI-OCR-MCZJ-fake_data_generator)
