### ISSUE TITLE
About data download

### ISSUE THREAD

**Issue by Mingtzge** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#10]
由于百度云盘链接很容易失效。所以需要数据的朋友请添加我为百度云盘好友，我的账号1713983016@@qq.com，我将通过好友分享的方式分享给大家，备注信息：”2019 CCF BDCI OCR 赛题数据“

**Comment by xiaolang564321** [comment]
@Mingtzge 怎么下载repitle_address_extract.json这个20多M的文件，我采用git lfs 下载
![image](https://user-images.githubusercontent.com/59152905/71867419-eeabe000-3144-11ea-9e09-3d8dee853958.png)无法下载这个数据

**Comment by Mingtzge** [comment]
由于 lfs功能已经超额失效，所以与lfs相关的文件会下载失败，相关的文件已经上传到这里 链接: https://pan.baidu.com/s/1ow51it9J8aK9OCTIx6NceA 提取码: 4i3r

**Comment by UTMOSTOF9** [comment]
It seems the download link is lost again.
Could you provide new link? Thanks!
