### ISSUE TITLE
关于签发机关纠正问题

### ISSUE THREAD

**Issue by lhn217** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#13]
大佬，项目中unit.json中签发机关的内容不太对，以’南京市栖霞区公安局‘为例，身份证背面的签发机关真正的内容为’南京市公安局栖霞分局‘，是还有其他转换逻辑吗？

**Comment by Mingtzge** [comment]
您好，我们也发现这个问题了，实际上赛题中的签发机关的数据是官方按照”地址前三级+公安局“简单的规则伪造的，所以跟真实的情况有出入。如果要应用到实际的情况下的话，把数据库文件更新成正确的即可，纠正逻辑还是照样适用。

**Comment by lhn217** [comment]
> 您好，我们也发现这个问题了，实际上赛题中的签发机关的数据是官方按照”地址前三级+公安局“简单的规则伪造的，所以跟真实的情况有出入。如果要应用到实际的情况下的话，把数据库文件更新成正确的即可，纠正逻辑还是照样适用。

好的，谢谢啦
