### ISSUE TITLE
是否可以提供论文和 ppt 的 pdf 链接？

### ISSUE THREAD

**Issue by animebing** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#16]
谢谢分享。[论文链接](https://discussion.datafountain.cn/questions/2232/answers/23321) 和 [ppt链接](https://discussion.datafountain.cn/questions/2260/answers/23380) 里的内容是 png 格式的，里边的图片看不清楚，是否可以提供 pdf 格式的，谢谢。

**Comment by Mingtzge** [comment]
上传到百度云了。链接: https://pan.baidu.com/s/1pHBmPS0x7vjfr4pw-cZIGA 提取码: 5ese

**Comment by animebing** [comment]
@Mingtzge 谢谢。
