### ISSUE TITLE
ctcloss的参数labels

### ISSUE THREAD

**Issue by iredescentone** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#17]
https://github.com/Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement/blob/6f11d683ab7bc044c0223fedfb15f8af74af1ae3/recognize_process/crnn_model/crnn_model.py#L136
看到您的tf版本是1.1.12，该版本ctcloss对应的输入label是一个稀疏矩阵，确认下您这行代码输入的labels是经过稀疏变换的吗？

**Comment by Wenqiang-Miao** [comment]
您好，在读取tfrecord文件的时候转化为sparse tensor了。
-------------------------------
非常感谢您的提问，这个问题我之前没有在意过；不过如果labels不是sparse tensor，调用ctc_loss会报错的。
