### ISSUE TITLE
文本检测方法

### ISSUE THREAD

**Issue by DataXujing** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#19]
文本检测咱们团队用的什么方法。。。。。

**Comment by Mingtzge** [comment]
你好，文本检测用的是CRNN模型，具体可参考[方案介绍](https://discussion.datafountain.cn/questions/2232/answers/23321)

**Comment by Wenqiang-Miao** [comment]
您好，因为身份证中各文本区域的位置是固定的，所以文本检测是直接基于坐标位置进行的。
