### ISSUE TITLE
请问下有数据集路径吗？

### ISSUE THREAD

**Issue by xtczq** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#2]

**Comment by Mingtzge** [comment]
赛题的数据可以在[下载地址](https://www.datafountain.cn/competitions/346/datasets)下载， 可能需要注册一下。训练数据比较大，上传下载都比较麻烦，因此我们提供了数据生成方法[源码](https://github.com/Mingtzge/2019-CCF-BDCI-OCR-MCZJ-fake_data_generator)，按照说明就能生成训练所需的训练数据

**Comment by wuxiaolianggit** [comment]
大佬，可以发一份源码和模型给我们，github上面一直下载不了，安装了git lfs也没下载成功， @Mingtzge @xtczq

**Comment by wuxiaolianggit** [comment]
1037675902@qq.com，这是我的邮箱 @xtczq @Mingtzge

**Comment by Mingtzge** [comment]
采用 lfs 保存的文件就只有文字识别和去水印的模型，模型我已经邮件给你发过去了！由于文件比较大，现在已经超出限额了，所以这个功能被停了，代码整体也可以通过百度云下载，链接: https://pan.baidu.com/s/15j5FHoKGmuuQ6LPIuRJsQw 提取码: i6dw

**Comment by lhn217** [comment]
这个数据集已经下不了了，能再给个路径吗

**Comment by Mingtzge** [comment]
把模型单独上传百度云了，希望不会被和谐！
链接: https://pan.baidu.com/s/1ow51it9J8aK9OCTIx6NceA 提取码: 4i3r

**Comment by lhn217** [comment]
> 把模型单独上传百度云了，希望不会被和谐！
> 链接: https://pan.baidu.com/s/1ow51it9J8aK9OCTIx6NceA 提取码: 4i3r

多谢大佬
