### ISSUE TITLE
身份证元素提取模板

### ISSUE THREAD

**Issue by virgilxiao** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#20]
你好~
身份证元素提取模板图片在template_imgs里面没有，能够提供一下吗，想研究一下模板匹配这一块的代码？

**Comment by Mingtzge** [comment]
你好，身份证元素提取时，是通过模板匹配，先获取的参考点的位置，再通过相对位置获取到身份证上面各个元素的位置，具体可参考我们的说明论文。所以，这部分用的模板图片是身份证左上角的“限BDCI”部分。即watermask_remover_and_split_data/template_imgs/origin_img_location_marker_template.jpg
