### ISSUE TITLE
请问识别模型为什么没有ckpt文件

### ISSUE THREAD

**Issue by upupbo** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#22]
请问识别模型为什么没有ckpt文件

**Comment by Mingtzge** [comment]
你好，模型文件在recognize_process/model_save/目录下

**Comment by zlszhonglongshen** [comment]
> 你好，模型文件在recognize_process/model_save/目录下

你好，在该文件下，没有找到对应的模型呢？

**Comment by Wenqiang-Miao** [comment]
> > 你好，模型文件在recognize_process/model_save/目录下
> 
> 你好，在该文件下，没有找到对应的模型呢？

您好，该目录下有的，麻烦您再确认一下？
