### ISSUE TITLE
测试程序运行出错

### ISSUE THREAD

**Issue by upupbo** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#23]
NameError                                 Traceback (most recent call last)
~/code/OCR/main_process.py in <module>()
     77     # 去水印和对图片进行切割和处理
     78     watermask_handler = WatermarkRemover(args, header_dir, cut_twisted_save_path)
---> 79     watermask_handler.watermask_remover_run()
     80     recognize_image_path = os.path.join(header_dir, "test_data_preprocessed")
     81     recognize_txt_path = os.path.join(header_dir, "test_data_txts")

~/code/OCR/watermask_remover_and_split_data/watermask_process.py in watermask_remover_run(self)
    222             self.gan_gen_result()
    223         if not args.no_rec_img:  # 将去好水印的图片恢复到原图
--> 224             print("running rec_img ....")
    225             self.recover_origin_img()
    226             self.ori_img_path = self.recover_image_dir  # 将原始图片路径改为去过水印之后的图片路径

~/code/OCR/watermask_remover_and_split_data/watermask_process.py in recover_origin_img(self)
    168         result_dir = os.path.join(self.gan_result_dir, self.pixel_mode, "test_latest", "images")
    169         if not os.path.exists(result_dir):
--> 170             print("not exists gan result dir")
    171             exit(0)
    172         result_img_names = os.listdir(result_dir)

NameError: name 'exit' is not defined

**Comment by Mingtzge** [comment]
Hello， i want to see your execution instructions and run directory
