### ISSUE TITLE
git-clone error with git-lfs

### ISSUE THREAD

**Issue by jackie930** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#24]
hi-我试图运行代码，但这个lfs文件无法下载，请问下有没有什么解决方案？感谢！～

git clone https://github.com/Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement.git
Cloning into '2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement'...
remote: Enumerating objects: 150, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 305 (delta 38), reused 97 (delta 11), pack-reused 155
Receiving objects: 100% (305/305), 1.82 MiB | 32.72 MiB/s, done.
Resolving deltas: 100% (56/56), done.
Downloading data_correction_and_generate_csv_file/data/repitle_address_extract.json (27 MB)
Error downloading object: data_correction_and_generate_csv_file/data/repitle_address_extract.json (f6021cc): Smudge error: Error downloading data_correction_and_generate_csv_file/data/repitle_address_extract.json (f6021cc1b6e451a4572698eedf9a48cfad2c14fdd392e6d9fcc8644541816f00): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /home/ec2-user/SageMaker/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement/.git/lfs/logs/20200218T054034.97028677.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: data_correction_and_generate_csv_file/data/repitle_address_extract.json: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by Mingtzge** [comment]
你好,由于文件大小超出限制,git-lfs功能失效了,所以不能通过git-lfs下载的数据只能 离线提供了,模型文件的下载地址:https://pan.baidu.com/s/1ow51it9J8aK9OCTIx6NceA 提取码: 4i3r,其他数据文件的获取可以参考readme和issue

**Comment by jackie930** [comment]
> 你好,由于文件大小超出限制,git-lfs功能失效了,所以不能通过git-lfs下载的数据只能 离线提供了,模型文件的下载地址:https://pan.baidu.com/s/1ow51it9J8aK9OCTIx6NceA 提取码: 4i3r,其他数据文件的获取可以参考readme和issue

您好-感谢回复！模型文件我已经通过网盘下载，这个报错的是 data_correction_and_generate_csv_file/data/repitle_address_extract.json  这个json文件，看起来用git-lfs依然超出下载带宽，不知道能否提供别的下载方式？
