### ISSUE TITLE
cut_twist_process中template生成方式

### ISSUE THREAD

**Issue by jackie930** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#27]
您好，当我使用自定义身份证图片进行测试时，发现twist模块将原本正着的图像进行了反转，我怀疑时用于进行比较的template中的模版图片的通用性不够，故而想自己生成。

想请教下，这里template文件的生成方式？是否是twist_part中的gaussian_blur函数即可？还是否需要进行灰度锐化等操作？

感谢！

**Comment by Wenqiang-Miao** [comment]
您好，template图片的生成方式就是gaussian_blur函数中的操作，没有进行锐化；

我们的想法是就是缩放图像的大小，然后对图片进行高斯模糊，忽略身份证中文字部分不同带来的影响，仅凭正反面轮廓的不同来实现分辨正反面；

不同的任务可能具体的做法不太一样（比赛的数据集比较规整，好分辨），您可以按照上面的思路更改一下处理的方法。
