### ISSUE TITLE
文字定位模型

### ISSUE THREAD

**Issue by DaisyLoveU** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#3]
请问文字定位模型使用的哪一个呢？可否提供呢？

**Comment by Mingtzge** [comment]
你好，我们的文本定位没有采用深度学习模型，采用的是传统的方法进行文本定位，具体方法见[赛题解决方案](https://discussion.datafountain.cn/questions/2232/answers/23321)中的关键文本定位模块

**Comment by DaisyLoveU** [comment]
多谢！
