### ISSUE TITLE
there are something wrong in test_data_dst_path, exit...

### ISSUE THREAD

**Issue by LinearPi** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#30]
![image](https://user-images.githubusercontent.com/29011350/75306465-1e917d00-5884-11ea-90ca-fc4f96235ed0.png)
执行到 watermask_remover_and_split_data/watermask_process.py 第253 行的函数时出现错误

**Comment by Mingtzge** [comment]
你好,请把错误提示信息贴一下吧

**Comment by LinearPi** [comment]
Linux 和 Windows 系统  复制文件的方式不一样 ，os.system("cp %s %s" % (os.path.join(self.ori_img_path, img), self.recover_image_dir + "/"))  执行有报错：'cp' 不是内部或外部命令，也不是可运行的程序或批处理文件。

**Comment by LinearPi** [comment]
可以使用 shutil 模块来进行复制
from shutil import copyfile
copyfile(os.path.join(self.ori_img_path, img), os.path.join(self.recover_image_dir + img))
