### ISSUE TITLE
CGAN data

### ISSUE THREAD

**Issue by cqray1990** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#31]
HI:
what datasets you train CGAN to erase watermark like?,i test an full image but the data you generate is not an full image,it's just a small picture which include watermark only

**Comment by Mingtzge** [comment]
hi, in order to increase the efficiency of training and decrease the calculation, we just use the watermark area of the image and resize the area as 256*256.
