### ISSUE TITLE
char_map.json文件生成方式

### ISSUE THREAD

**Issue by jackie930** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#32]
您好，

我想用自己的数据集finetune一下这个crnn的模型，想请教一下，训练用到的char_map.json是否为一个自己生成的字典文件？根据自己的训练数据里面出现的字符列出即可？
另外，在annotation file里面是不是就是 path/xxx.jpg 标注文字这样的格式的一个标注文件？标注文字是没有根据字典文件转换index的？
想确认一下数据格式是否正确！感谢！

**Comment by Wenqiang-Miao** [comment]
您好：
char_map.json是根据自己的训练数据集生成的，包含所有字符即可。
标注文件格式是文件名+空格+标签，标签是自然文本，没有经过转化，类似这样：
0.jpg ﻿715698882768615325
1.jpg 霍州市高湾乡谢集村
