### ISSUE TITLE
Some question on Pix2Pix

### ISSUE THREAD

**Issue by willhunger** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#33]
Hey, You mentioned you make some modifications to the Pix2pix model in [this repo](https://github.com/Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement/tree/master/pytorch-CycleGAN-and-pix2pix).

Roughly checking your repo and original Pix2Pix model, I got these modifications below:
* Added  `--add_contrast` in `base_options.py`
* Commented the Visualizer part
* Changed a function into lambda function in 'get_norm_layer' from `networks.py`

I wonder is there more modification on the Pix2Pix part of your repo?  You also claimed you make data augmentation and could you please add more detail of that?

**Comment by Mingtzge** [comment]
hi,  you have mentioned most of the modifications. The other modifications are some default parameters mainly, for example, the size of input/output images and the epoch counts setting.

the `--add_contrast` option is about the data augmentation,which aims to change the contrast and brightness randomly. details see pytorch-CycleGAN-and-pix2pix/data/aligned_dataset.py in 48 row.

**Comment by willhunger** [comment]
Thanks, buddy
