### ISSUE TITLE
百度网盘分享失效，跪求留个联系方式，感激不尽，QQ 83656313

### ISSUE THREAD

**Issue by xianglei3** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#35]

**Comment by WingGun** [comment]
您好，
不好意思我不是这个项目的原作者，原项目的网址在这里https://github.com/Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement
给您造成的不便还请谅解




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xianglei3"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月14日(星期四) 晚上8:35
收件人:&nbsp;"Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement"<2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement] 百度网盘分享失效，跪求留个联系方式，感激不尽，QQ 83656313 (#35)

**Comment by Mingtzge** [comment]
email:1713983016@qq.com
