### ISSUE TITLE
百度云盘分享失效了，跪求，跪求 ，感谢恩师，QQ 83656313

### ISSUE THREAD

**Issue by xianglei3** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#36]

**Comment by Mingtzge** [comment]
i have sent a friend request, but you did not  respond

**Comment by annluda** [comment]
> i have sent a friend request, but you did not respond

同求，邮箱anld2017@163.com

**Comment by TANGELIAN** [comment]
同求，先生加我，QQ841161761

**Comment by fireae007** [comment]
同求，faruxue007@163.com, 万分感谢

**Comment by zhangkangzh** [comment]
同求，1543554013@qq.com

**Comment by guanfaqian** [comment]
同求，guanfaqian@163.com

**Comment by pyh109** [comment]
同求 1832922978@qq.com　　 万分感谢

**Comment by Mingtzge** [comment]
需要的，加我百度网盘好友1713983016@qq.com

**Comment by tim120526** [comment]
> 需要的，加我百度网盘好友[1713983016@qq.com](mailto:1713983016@qq.com)

已加
