### ISSUE TITLE
地址纠正repitle_address_extract.json文件下载

### ISSUE THREAD

**Issue by fangqin0703** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#5]
作者能不能分享一下repitle_address_extract.json文件，这个好像也下载不了，谢谢！

**Comment by leewi9** [comment]
有没有好心人可以分享一下这个比赛的数据集？

**Comment by Mingtzge** [comment]
> 作者能不能分享一下repitle_address_extract.json文件，这个好像也下载不了，谢谢！

链接: https://pan.baidu.com/s/1XaiQWodsw-0oaiAbpa7NHg 提取码: ygpn 
添加到百度云模型文件下面了
