### ISSUE TITLE
可以提供下复赛数据集吗

### ISSUE THREAD

**Issue by upupbo** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#6]

**Comment by iredescentone** [comment]
同问，求初赛和复赛的数据下载

**Comment by Mingtzge** [comment]
链接: https://pan.baidu.com/s/182lB5Wfz39Lkm7T4VyKOvw 提取码: 52gg初赛和复赛的数据都在这里

**Comment by Mingtzge** [comment]
赛题数据链接很快就被和谐了，可能因为是有身份证图片，初赛数据可以直接从[官网](https://www.datafountain.cn/competitions/346/datasets)下载。复赛的数据如果有需要的，发我邮件吧mingzjiang@qq.com
