### ISSUE TITLE
the data link have been lost by baidu

### ISSUE THREAD

**Issue by QuntuamLoop** [Mingtzge/2019-CCF-BDCI-OCR-MCZJ-OCR-IdentificationIDElement#7]
Hi, same to the title of the title link.  the data of the model has been block by baidu. Could you reload the data again?

**Comment by Mingtzge** [comment]
链接: https://pan.baidu.com/s/1Ixtfrf9Wii-1OChvuIQ1HA 提取码: whki 
Please fetch the data as soon as possible or it will fail again

**Comment by yaoing** [comment]
lost again

**Comment by JimmyHHua** [comment]
> 链接: https://pan.baidu.com/s/1Ixtfrf9Wii-1OChvuIQ1HA 提取码: whki
> Please fetch the data as soon as possible or it will fail again

Can u seed it again?

**Comment by Mingtzge** [comment]
ok， please refer to the #10

**Comment by JimmyHHua** [comment]
> ok， please refer to the #10
已申请~
